import { AuthResponses } from "./auth.types";

export const AUTH_RESPONSES = {
  INVALID_CREDENTIALS: new AuthResponses(401, "INVALID CREDENTIALS"),
  INTERNAL: new AuthResponses(500, "USER NOT CREATED"),
  SIGNUP_SUCCESSFUL: new AuthResponses(200, "USER CREATED SUCCESSFULLY"),
  ALREADY_EXIST: new AuthResponses(409, "USER ALREADY EXISTS"),
  NOT_FOUND: new AuthResponses(404, "USER NOT FOUND"),
  LOGIN_SUCCESSFUL: new AuthResponses(200, "LOGIN SUCCESSFUL"),
  LOGOUT_SUCCESSFUL: new AuthResponses(200, "LOGOUT SUCCESSFUL"),
  CANNOT_UPDATE: new AuthResponses(400, "USER CANNOT BE UPDATED"),
  RESET_PASSWORD_LINK_SENT: new AuthResponses(
    200,
    "RESET PASSWORD LINK HAS BEEN SUCCESSFULLY SENT TO YOUR REGISTERED EMAIL ID"
  ),
  PASSWORD_RESET: new AuthResponses(
    200,
    "PASSWORD HAS BEEN SUCCESSFULLY RESET"
  ),
};
